databases:
  - name: mysitedb
    plan: free
    databaseName: todomodel
    user: ryo

services:
  - type: web
    plan: free
    name: todo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn todoproject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
